/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PainelLeads9f3k7x2pq8mRouteImport } from './routes/painel-leads-9f3k7x2pq8m'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLeads9f3k7x2pq8mRoute = PainelLeads9f3k7x2pq8mRouteImport.update({
  id: '/painel-leads-9f3k7x2pq8m',
  path: '/painel-leads-9f3k7x2pq8m',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel-leads-9f3k7x2pq8m': typeof PainelLeads9f3k7x2pq8mRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel-leads-9f3k7x2pq8m': typeof PainelLeads9f3k7x2pq8mRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel-leads-9f3k7x2pq8m': typeof PainelLeads9f3k7x2pq8mRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel-leads-9f3k7x2pq8m' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel-leads-9f3k7x2pq8m' | '/sitemap.xml'
  id: '__root__' | '/' | '/painel-leads-9f3k7x2pq8m' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelLeads9f3k7x2pq8mRoute: typeof PainelLeads9f3k7x2pq8mRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-leads-9f3k7x2pq8m': {
      id: '/painel-leads-9f3k7x2pq8m'
      path: '/painel-leads-9f3k7x2pq8m'
      fullPath: '/painel-leads-9f3k7x2pq8m'
      preLoaderRoute: typeof PainelLeads9f3k7x2pq8mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelLeads9f3k7x2pq8mRoute: PainelLeads9f3k7x2pq8mRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
